vim.g.mapleader = ";"
vim.api.nvim_set_keymap('n', '', 'g', {})
vim.api.nvim_set_keymap('n', '<F8>', ':TagbarToggle<CR>', {})
vim.api.nvim_set_keymap('n', '<leader><leader>', ':Telescope git_files<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>g', ':Telescope live_grep<CR>', {})
vim.api.nvim_set_keymap('n', '<leader>s', ':Gitsigns stage_hunk<CR>', {})
vim.api.nvim_set_keymap('n', 'E', ':bp<CR>', {})
vim.api.nvim_set_keymap('n', 'H', '10h', {})
vim.api.nvim_set_keymap('n', 'J', '5j', {})
vim.api.nvim_set_keymap('n', 'K', '5k', {})
vim.api.nvim_set_keymap('n', 'L', '10l', {})
vim.api.nvim_set_keymap('n', '``', ':buffer#<CR>', {})
vim.api.nvim_set_keymap('n', 'e', ':bn<CR>', {})
vim.api.nvim_set_keymap('n', 't', ':Telescope<CR>', {})
vim.api.nvim_set_keymap('v', 'H', '10h', {})
vim.api.nvim_set_keymap('v', 'J', '5j', {})
vim.api.nvim_set_keymap('v', 'K', '5k', {})
vim.api.nvim_set_keymap('v', 'L', '10l', {})
vim.api.nvim_set_keymap('v', 's', ':sort<cr>', {})
vim.keymap.set('n', '<leader>e', vim.diagnostic.open_float, {})
vim.keymap.set('n', '<leader>n', vim.diagnostic.goto_prev, {})
vim.keymap.set('n', '<leader>p', vim.diagnostic.goto_next, {})
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, {})
vim.keymap.set('n', '<leader>ca', vim.lsp.buf.code_action, {})
vim.keymap.set('n', '<leader>f', vim.lsp.buf.format, {})
--vim.keymap.set('n', '<leader>z', vim.lsp.codelens.refresh, {})
